name: Herz analog
favicon: null
layout_spectrum: 0.77965
typography_spectrum: 0.5917
title: Herz analog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#299597'
    - '#151611'
    - '#3e4a40'
    - '#79b3b5'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
