typography_spectrum: 0.5917
color:
  brandColors:
    - '#ffffff'
    - '#299597'
    - '#151611'
    - '#3e4a40'
    - '#79b3b5'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.77965
analytics:
  google: null
  facebook: null
  twitter: null
name: Herz analog
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Herz analog
description: 'herzanalog,'
purpose: []
