name: Herz analog
favicon: null
layout_spectrum: 0.26493
typography_spectrum: 0.5917
title: Herz analog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#ffffff'
    - '#c9d0d8'
    - '#7b8faa'
    - '#454a4e'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
